[package]
name = "sys-audio-filter"
version = "0.1.0"
authors = ["Anton Kriese (WSL2) <anton.kriese@fu-berlin.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.3"
rodio = "0.13.1"
anyhow = "1.0.40"

